### PR TITLE
chore: introduce konfik

### PR DESCRIPTION
**Pull request by mikearnaldi**

### CODE REVIEW

**Review by IMax153 — APPROVED** [review]
This PR looks good, but the CI-CD pipe is failing.

**Comment by schickling** [comment]
What was the problem with the `postinstall`?

**Comment by mikearnaldi** [comment]
The target ES version is too high for the node version used, for
compatibility the bundled output should be plain es5/6

**Comment by mikearnaldi** [comment]
Given the dependency between konfik and effect we won't be able to use konfik in this repo

**Comment by schickling** [comment]
I think that's a misunderstanding. Effect shouldn't be a "transparent" dependency of Konfik as it is bundled into the Konfik CLI.

**Comment by mikearnaldi** [comment]
Not if the model changes to allow plugins to use effect and given the model is still in discussion I'd delay until stable

**Pull request closed without merging**
